# Generated by Django 5.1.4 on 2025-01-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zuventure_app', '0003_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SisterConcern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='sister-concern')),
            ],
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name_plural': 'Product Categories'},
        ),
        migrations.AddField(
            model_name='product',
            name='product_of',
            field=models.ManyToManyField(to='zuventure_app.sisterconcern'),
        ),
    ]
