# Generated by Django 5.1.4 on 2025-01-09 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zuventure_app', '0004_sisterconcern_alter_productcategory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_of',
        ),
        migrations.AddField(
            model_name='product',
            name='product_of',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='zuventure_app.sisterconcern'),
        ),
    ]
