# Generated by Django 5.1.4 on 2025-01-09 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zuventure_app', '0006_alter_product_product_of'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='about-images')),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'About Us',
            },
        ),
        migrations.CreateModel(
            name='SliderView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('sub_title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Slider View',
            },
        ),
        migrations.AlterModelOptions(
            name='sisterconcern',
            options={'verbose_name_plural': 'Sister Concerns'},
        ),
        migrations.AlterField(
            model_name='sisterconcern',
            name='image',
            field=models.ImageField(upload_to='sister-concern-images'),
        ),
    ]
