# Generated by Django 5.1.4 on 2025-01-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zuventure_app', '0007_aboutus_sliderview_alter_sisterconcern_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderview',
            name='image',
            field=models.ImageField(null=True, upload_to='slider-images'),
        ),
    ]
