# Generated by Django 5.1.4 on 2025-01-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zuventure_app', '0009_featureproduct_alter_product_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery-images')),
                ('short_description', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Gallery',
            },
        ),
    ]
