# Generated by Django 5.1.4 on 2025-01-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zuventure_app', '0010_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='short_description',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
