# Generated by Django 5.1.4 on 2025-01-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zuventure_app', '0011_alter_gallery_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='short_description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
