# Generated by Django 5.1.4 on 2025-01-09 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zuventure_app', '0013_product_is_popular'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='logo')),
                ('primary_phone', models.IntegerField(max_length=15)),
                ('secondary_phone', models.IntegerField(blank=True, max_length=15, null=True)),
                ('location', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Company Informations',
            },
        ),
        migrations.AlterModelOptions(
            name='featureproduct',
            options={'verbose_name_plural': 'Feature Product'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
    ]
