# Generated by Django 5.1.4 on 2025-01-09 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zuventure_app', '0014_company_info_alter_featureproduct_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company_info',
            new_name='CompanyInfo',
        ),
    ]
