# Generated by Django 5.1.4 on 2025-01-09 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zuventure_app', '0015_rename_company_info_companyinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='primary_phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='secondary_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
