# Generated by Django 5.1.4 on 2025-01-09 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zuventure_app', '0016_alter_companyinfo_primary_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
