# Generated by Django 5.1.4 on 2025-01-09 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zuventure_app', '0017_companyinfo_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='facebook_url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='instagram_url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='linkdin_url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='youtube_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
