# Generated by Django 5.1.4 on 2025-01-10 09:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zuventure_app', '0021_contact_delete_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='descriptions',
            field=ckeditor.fields.RichTextField(max_length=10000),
        ),
    ]
