# Generated by Django 5.1.4 on 2025-01-10 16:31

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zuventure_app', '0022_alter_product_descriptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chairman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='chairman-image')),
                ('description', ckeditor.fields.RichTextField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='ManagingDirector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='md-image')),
                ('description', ckeditor.fields.RichTextField(max_length=10000)),
            ],
        ),
    ]
