# Generated by Django 5.1.4 on 2025-01-10 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zuventure_app', '0023_chairman_managingdirector'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='Team-images')),
                ('designation', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Team Members',
            },
        ),
        migrations.DeleteModel(
            name='FeatureProduct',
        ),
        migrations.AlterModelOptions(
            name='chairman',
            options={'verbose_name_plural': 'Chairman'},
        ),
        migrations.AlterModelOptions(
            name='managingdirector',
            options={'verbose_name_plural': 'Managing Director'},
        ),
    ]
