# Generated by Django 5.1.4 on 2025-01-10 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zuventure_app', '0024_teammember_delete_featureproduct_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CvCatagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Cv Category',
            },
        ),
        migrations.CreateModel(
            name='DropCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='cv_photo/')),
                ('cv', models.FileField(blank=True, null=True, upload_to='cv_pdf/')),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('cv_catagory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zuventure_app.cvcatagory')),
            ],
            options={
                'verbose_name_plural': 'Dropped CV',
            },
        ),
    ]
